package gltf

const (
	keyAsset       = "asset"
	keyScene       = "scene"
	keyScenes      = "scenes"
	keyNodes       = "nodes"
	keyMeshes      = "meshes"
	keyMaterials   = "materials"
	keyCameras     = "cameras"
	keySkins       = "skins"
	keyAnimations  = "animations"
	keyAccessors   = "accessors"
	keyBufferViews = "bufferViews"
	keyBuffers     = "buffers"
	keyTextures    = "textures"
	keyImages      = "images"
	keySamplers    = "samplers"

	keyName       = "name"
	keyVersion    = "version"
	keyGenerator  = "generator"
	keyBuffer     = "buffer"
	keyByteOffset = "byteOffset"
	keyByteLength = "byteLength"
	keyByteStride = "byteStride"

	keyBufferView    = "bufferView"
	keyComponentType = "componentType"
	keyCount         = "count"
	keyType          = "type"

	keyMesh        = "mesh"
	keySkin        = "skin"
	keyCamera      = "camera"
	keyChildren    = "children"
	keyMatrix      = "matrix"
	keyTranslation = "translation"
	keyRotation    = "rotation"
	keyScale       = "scale"
	keyWeights     = "weights"

	keyPrimitives = "primitives"
	keyAttributes = "attributes"
	keyIndices    = "indices"
	keyMaterial   = "material"
	keyMode       = "mode"
	keyFilter     = "filter"
	keyTargets    = "targets"

	attrPosition        = "POSITION"
	attrNormal          = "NORMAL"
	attrTangent         = "TANGENT"
	attrTexCoord0       = "TEXCOORD_0"
	attrTexCoord1       = "TEXCOORD_1"
	attrTexCoord2       = "TEXCOORD_2"
	attrTexCoord3       = "TEXCOORD_3"
	attrColor0          = "COLOR_0"
	attrJoints0         = "JOINTS_0"
	attrJoints1         = "JOINTS_1"
	attrWeights0        = "WEIGHTS_0"
	attrWeights1        = "WEIGHTS_1"
	attrInstTranslation = "TRANSLATION"
	attrInstRotation    = "ROTATION"
	attrInstScale       = "SCALE"

	keyAlphaMode            = "alphaMode"
	keyAlphaCutoff          = "alphaCutoff"
	keyDoubleSided          = "doubleSided"
	keyPBRMetallicRoughness = "pbrMetallicRoughness"
	keyBaseColorFactor      = "baseColorFactor"
	keyMetallicFactor       = "metallicFactor"
	keyRoughnessFactor      = "roughnessFactor"
	keyBaseColorTexture     = "baseColorTexture"
	keyMetRoughTexture      = "metallicRoughnessTexture"
	keyNormalTexture        = "normalTexture"
	keyOcclusionTexture     = "occlusionTexture"
	keyEmissiveFactor       = "emissiveFactor"
	keyEmissiveTexture      = "emissiveTexture"
	keyIndex                = "index"
	keyTexCoord             = "texCoord"
	keyStrength             = "strength"
	keyNormalScale          = "scale"

	keyChannels      = "channels"
	keySampler       = "sampler"
	keyInput         = "input"
	keyOutput        = "output"
	keyTarget        = "target"
	keyPath          = "path"
	keyNode          = "node"
	keyInterpolation = "interpolation"

	keyPerspective  = "perspective"
	keyOrthographic = "orthographic"
	keyYfov         = "yfov"
	keyZnear        = "znear"
	keyZfar         = "zfar"
	keyAspectRatio  = "aspectRatio"
	keyXmag         = "xmag"
	keyYmag         = "ymag"

	keySource    = "source"
	keyMimeType  = "mimeType"
	keyURI       = "uri"
	keyOffset    = "offset"
	keyWrapS     = "wrapS"
	keyWrapT     = "wrapT"
	keyMinFilter = "minFilter"
	keyMagFilter = "magFilter"

	keySkeleton            = "skeleton"
	keyJoints              = "joints"
	keyInverseBindMatrices = "inverseBindMatrices"

	keyExtensions         = "extensions"
	keyExtensionsRequired = "extensionsRequired"
	keyExtensionsUsed     = "extensionsUsed"
	keyExtras             = "extras"

	keySparse        = "sparse"
	keySparseIndices = "indices"
	keySparseValues  = "values"

	keyKHRMaterialsUnlit   = "KHR_materials_unlit"
	keyKHRTextureBasisu    = "KHR_texture_basisu"
	keyKHRTextureTransform = "KHR_texture_transform"

	keyKHRLightsPunctual = "KHR_lights_punctual"
	keyLights            = "lights"
	keyLight             = "light"
	keyColor             = "color"
	keyIntensity         = "intensity"
	keyRange             = "range"
	keySpot              = "spot"
	keyInnerConeAngle    = "innerConeAngle"
	keyOuterConeAngle    = "outerConeAngle"

	keyKHRClearcoat        = "KHR_materials_clearcoat"
	keyKHRSheen            = "KHR_materials_sheen"
	keyKHRTransmission     = "KHR_materials_transmission"
	keyKHRVolume           = "KHR_materials_volume"
	keyKHRIOR              = "KHR_materials_ior"
	keyKHRSpecular         = "KHR_materials_specular"
	keyKHRAnisotropy       = "KHR_materials_anisotropy"
	keyKHRIridescence      = "KHR_materials_iridescence"
	keyKHREmissiveStrength = "KHR_materials_emissive_strength"
	keyKHRMatVariants      = "KHR_materials_variants"
	keyMSFTLOD             = "MSFT_lod"
	keyMSFTScreenCoverage  = "MSFT_screencoverage"
	keyEXTTextureWebP      = "EXT_texture_webp"
	keyEXTMeshGPUInst      = "EXT_mesh_gpu_instancing"
	keyEXTMeshoptComp      = "EXT_meshopt_compression"
	keyIDs                 = "ids"
	keyVariants            = "variants"
	keyMappings            = "mappings"
	keyEmissiveStrength    = "emissiveStrength"
	keyAttributesInst      = "attributes"

	keyClearcoatFactor           = "clearcoatFactor"
	keyClearcoatRoughnessFactor  = "clearcoatRoughnessFactor"
	keyClearcoatTexture          = "clearcoatTexture"
	keyClearcoatRoughnessTexture = "clearcoatRoughnessTexture"
	keyClearcoatNormalTexture    = "clearcoatNormalTexture"

	keySheenColorFactor      = "sheenColorFactor"
	keySheenRoughnessFactor  = "sheenRoughnessFactor"
	keySheenColorTexture     = "sheenColorTexture"
	keySheenRoughnessTexture = "sheenRoughnessTexture"

	keyTransmissionFactor  = "transmissionFactor"
	keyTransmissionTexture = "transmissionTexture"

	keyThicknessFactor     = "thicknessFactor"
	keyThicknessTexture    = "thicknessTexture"
	keyAttenuationDistance = "attenuationDistance"
	keyAttenuationColor    = "attenuationColor"

	keyIOR = "ior"

	keySpecularFactor       = "specularFactor"
	keySpecularColorFactor  = "specularColorFactor"
	keySpecularTexture      = "specularTexture"
	keySpecularColorTexture = "specularColorTexture"

	keyAnisotropyStrength = "anisotropyStrength"
	keyAnisotropyRotation = "anisotropyRotation"
	keyAnisotropyTexture  = "anisotropyTexture"

	keyIridescenceFactor           = "iridescenceFactor"
	keyIridescenceTexture          = "iridescenceTexture"
	keyIridescenceIor              = "iridescenceIor"
	keyIridescenceThicknessMinimum = "iridescenceThicknessMinimum"
	keyIridescenceThicknessMaximum = "iridescenceThicknessMaximum"
	keyIridescenceThicknessTexture = "iridescenceThicknessTexture"

	keyKHRPBRSpecGloss           = "KHR_materials_pbrSpecularGlossiness"
	keyDiffuseFactor             = "diffuseFactor"
	keyDiffuseTexture            = "diffuseTexture"
	keySpecGlossSpecularFactor   = "specularFactor"
	keyGlossinessFactor          = "glossinessFactor"
	keySpecularGlossinessTexture = "specularGlossinessTexture"

	keyKHRDispersion = "KHR_materials_dispersion"
	keyDispersion    = "dispersion"

	keyKHRDiffuseTransmission          = "KHR_materials_diffuse_transmission"
	keyDiffuseTransmissionFactor       = "diffuseTransmissionFactor"
	keyDiffuseTransmissionTexture      = "diffuseTransmissionTexture"
	keyDiffuseTransmissionColorFactor  = "diffuseTransmissionColorFactor"
	keyDiffuseTransmissionColorTexture = "diffuseTransmissionColorTexture"

	keyKHRAnimationPointer = "KHR_animation_pointer"
	keyPointer             = "pointer"
	pathPointer            = "pointer"
)
